version: '3'
services:
  db_users:
    container_name: "db_users"
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis_token:
    image: redis:7.2-rc2
    restart: on-failure

  auth:
    build: .
    env_file:
      - .env
    depends_on:
      - redis_token
      - db_users

volumes:
  postgres_data:


