version: '3'


services:
  db_users:
    image: postgres:13
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis_token:
    image: redis:7.2-rc2
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    restart: on-failure

  auth:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - redis_token
      - db_users

volumes:
  postgres_data:
