version: '3'


services:
  db_users:
    image: postgres:13
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis_token:
    image: redis:7.2-rc2
    restart: on-failure

  auth:
    build: .
    env_file:
      - .env
    depends_on:
      - redis_token
      - db_users


  nginx:
    image: nginx:1.25.1-alpine
    depends_on:
      - auth
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/conf.d:ro

volumes:
  postgres_data: