"""create ondelete=CASCADE


Revision ID: 51e714489d64
Revises: 906596ac77d0
Create Date: 2023-08-30 12:30:37.262842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e714489d64'
down_revision = '906596ac77d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
