"""onupdate=CASCADE

Revision ID: 68111ec498a3
Revises: 51e714489d64
Create Date: 2023-08-30 12:53:46.304327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68111ec498a3'
down_revision = '51e714489d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entry_user_id_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key(None, 'entry', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'role', ['role_id'], ['uuid'])
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'users', ['user_id'], ['uuid'])
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key('entry_user_id_fkey', 'entry', 'users', ['user_id'], ['uuid'])
    # ### end Alembic commands ###
