"""create cascade deletion

Revision ID: 906596ac77d0
Revises: e62177fd9e7f
Create Date: 2023-08-29 20:55:01.229516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906596ac77d0'
down_revision = 'e62177fd9e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
