"""create table user_socials

Revision ID: e62177fd9e7f
Revises: 087e0215143f
Create Date: 2023-08-29 20:13:53.027956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62177fd9e7f'
down_revision = '087e0215143f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_socials',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('sub_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_constraint('users_password_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.drop_table('user_socials')
    # ### end Alembic commands ###
