"""create table user

Revision ID: 06387a2ebc90
Revises: 675c6a29faf8
Create Date: 2023-08-01 12:10:38.053572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06387a2ebc90'
down_revision = '675c6a29faf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['login'])
    op.drop_column('users', 'history')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('history', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
